version: '3'
volumes:
  nestjs-node-modules:
   
services:
  attendance_app:
    build: .
    restart: always
    #added for hot reloading
    volumes:
      - .:/app
      - nestjs-node-modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
      
      #added for debug
      - 9229:9229